### ISSUE TITLE
dns-fuzz not public

### ISSUE THREAD

**Issue by sebdeckers** [dpb587/dns-test-server#1]
Hi @dpb587, I tried installing this but the dns-fuzz repo is not available. Any chance of making it public? Thank you.

**Comment by dpb587** [comment]
Hi - seems I renamed the repository at some point. Feel free to try again. Your mileage may vary; this was for some internal testing a while back.

**Comment by sebdeckers** [comment]
Thank you! I'm new to Go; didn't realise it was the same repo but renamed. 🤦🏼‍♂️
